# Generated by Django 5.2.6 on 2025-10-01 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='profiles.sitterprofile')),
            ],
            options={
                'ordering': ['start_ts'],
            },
        ),
    ]
