# Generated by Django 5.2.6 on 2025-10-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabilityslot",
            name="is_recurring",
        ),
    ]
