# Generated by Django 5.2.6 on 2025-10-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("house_sitting", "House Sitting"),
                    ("pet_boarding", "Pet Boarding"),
                    ("in_home_visit", "In-Home Visit"),
                    ("pet_grooming", "Pet Grooming"),
                    ("pet_walking", "Pet Walking"),
                ],
                default="house_sitting",
                max_length=20,
            ),
        ),
    ]
