# Generated by Django 5.2.6 on 2025-11-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_service_type"),
        ("profiles", "0005_alter_ownerprofile_banner_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pets",
            field=models.ManyToManyField(related_name="bookings", to="profiles.pet"),
        ),
    ]
