# Generated by Django 5.2.6 on 2025-10-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_tag_sitterprofile_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitterprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='sitters', to='profiles.specialty'),
        ),
    ]
