# Generated by Django 5.2.6 on 2025-10-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_specialty_sitterprofile_specialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerprofile",
            name="banner_picture",
            field=models.ImageField(
                blank=True,
                default="owner_banners/default_banner.png",
                null=True,
                upload_to="owner_banners/",
            ),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="owner_profiles/default_profile.png",
                null=True,
                upload_to="owner_profiles/",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="pet_profiles/default_banner.png",
                null=True,
                upload_to="pet_profiles/",
            ),
        ),
        migrations.AddField(
            model_name="sitterprofile",
            name="banner_picture",
            field=models.ImageField(
                blank=True,
                default="sitter_banners/default_banner.png",
                null=True,
                upload_to="sitter_banners/",
            ),
        ),
        migrations.AddField(
            model_name="sitterprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="sitter_profiles/default_banner.png",
                null=True,
                upload_to="sitter_profiles/",
            ),
        ),
    ]
