# Generated by Django 5.2.6 on 2025-10-30 20:10

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_ownerprofile_banner_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerprofile",
            name="banner_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.owner_banner_picture_path,
            ),
        ),
        migrations.AlterField(
            model_name="ownerprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.owner_profile_picture_path,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.pet_profile_picture_path,
            ),
        ),
        migrations.AlterField(
            model_name="sitterprofile",
            name="banner_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.sitter_banner_picture_path,
            ),
        ),
        migrations.AlterField(
            model_name="sitterprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.sitter_profile_picture_path,
            ),
        ),
    ]
