# Generated by Django 5.2.6 on 2025-11-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_ownerprofile_banner_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
