# Generated by Django 5.2.6 on 2025-11-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_sitterprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerprofile",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="ownerprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitterprofile",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitterprofile",
            name="home_zip",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitterprofile",
            name="rate_hourly",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
