# Generated by Django 5.2.6 on 2025-10-16 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagethread',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(fields=('booking', 'user_a', 'user_b'), name='uniq_thread_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', True)), fields=('user_a', 'user_b'), name='uniq_thread_pair_when_booking_null'),
        ),
    ]
