# Generated by Django 5.2.6 on 2025-11-01 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_service_type"),
        ("messaging", "0002_alter_messagethread_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="messagethread",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_a", models.F("user_b")), _negated=True),
                name="different_participants",
            ),
        ),
    ]
