# Generated by Django 5.2.6 on 2025-10-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("profiles", "0003_specialty_sitterprofile_specialties"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="booking.booking",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("booking", "sitter")},
        ),
    ]
